[toolchain]
channel = "nightly-2026-04-27"
profile = "minimal"
components = [
    "rustfmt",
    "clippy",
    "rust-src",
    "miri",
    "llvm-tools-preview",
]
targets = [
    "x86_64-unknown-linux-gnu",
]

[build]
# Allow the nightly features we use
rustflags = [
    "-Zallow-features=portable_simd,try_blocks",
]