[build]
rustflags = ["-Zallow-features=portable_simd,try_blocks"]

[toolchain]
channel = "1.94.0"
components = [
    "rustfmt",
    "clippy",
    "rust-src",
    "miri",
    "llvm-tools-preview",
]
profile = "minimal"
targets = ["x86_64-unknown-linux-gnu"]
