//! BDD Behavioral Contract Verification for twerk-app
//!
//! This test suite verifies behavioral contracts using Given/When/Then
//! structure against the public API. Three lenses applied:
//! - **Liar Check**: Does the implementation match its claims?
//! - **Breakage Check**: What happens when conditions degrade?
//! - **Completeness Check**: Is every public item exercised?
//!
//! Generated by bdd-enforcer for bead tw-dji.

#![allow(clippy::unwrap_used)]
#![allow(clippy::redundant_pattern_matching)]

use std::sync::atomic::{AtomicUsize, Ordering};
use std::sync::Arc;
use twerk_app::engine::broker::BrokerType;
use twerk_app::engine::coordinator::hostenv::HostEnv;
use twerk_app::engine::endpoints::EndpointRegistry;
use twerk_app::engine::middleware::MiddlewareComposer;
use twerk_app::engine::mounts::MountRegistry;
use twerk_app::engine::providers::ProviderRegistry;
use twerk_app::engine::worker::mounter::{
    BindConfig, BindMounter, MountPolicy, TmpfsMounter, VolumeMounter,
};
use twerk_app::engine::worker::Limits;
use twerk_app::engine::{
    BrokerProxy, Config, DatastoreProxy, EndpointHandler, Engine, JobEventType, JobHandlerError,
    JobListener, LogHandlerError, Middleware, Mode, NodeHandlerError, State, TaskEventType,
    TaskHandlerError,
};
use twerk_core::id::JobId;
use twerk_core::job::{Job, JobState};
use twerk_core::mount::Mount;
use twerk_core::task::{Task, TaskState};
use twerk_infrastructure::broker::{inmemory::InMemoryBroker, Broker};
use twerk_infrastructure::datastore::{inmemory::InMemoryDatastore, Datastore};
use twerk_infrastructure::runtime::{Mounter, Runtime};

// ─── Helpers ─────────────────────────────────────────────────────────

fn engine_with_mode(mode: Mode) -> Engine {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    std::env::set_var("TWERK_BROKER_TYPE", "inmemory");
    Engine::new(Config {
        mode,
        ..Default::default()
    })
}

fn to_job_id(value: impl Into<String>) -> JobId {
    JobId::new(value).expect("test job id should be valid")
}

fn make_job(id: &str) -> Job {
    Job {
        id: Some(to_job_id(id)),
        state: JobState::Pending,
        tasks: Some(vec![Task {
            name: Some("bdd-task".to_string()),
            image: Some("alpine".to_string()),
            run: Some("echo bdd".to_string()),
            ..Default::default()
        }]),
        task_count: 1,
        ..Default::default()
    }
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 1: STATE MACHINE CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: State defaults to Idle ---
#[test]
fn state_default_is_idle() {
    assert_eq!(State::default(), State::Idle);
}

// --- Claim: Mode defaults to Standalone ---
#[test]
fn mode_default_is_standalone() {
    assert_eq!(Mode::default(), Mode::Standalone);
}

// --- Claim: Only Terminated is terminal ---
#[test]
fn only_terminated_is_terminal() {
    assert!(!State::Idle.is_terminal());
    assert!(!State::Running.is_terminal());
    assert!(!State::Terminating.is_terminal());
    assert!(State::Terminated.is_terminal());
}

// --- Claim: Idle can transition to any state ---
#[test]
fn idle_can_transition_to_any_state() {
    assert!(State::Idle.can_transition_to(State::Idle));
    assert!(State::Idle.can_transition_to(State::Running));
    assert!(State::Idle.can_transition_to(State::Terminating));
    assert!(State::Idle.can_transition_to(State::Terminated));
}

// --- Claim: Running can only transition to Terminating ---
#[test]
fn running_can_only_transition_to_terminating() {
    assert!(State::Running.can_transition_to(State::Terminating));
    assert!(!State::Running.can_transition_to(State::Idle));
    assert!(!State::Running.can_transition_to(State::Running));
    assert!(!State::Running.can_transition_to(State::Terminated));
}

// --- Claim: Terminating can only transition to Terminated ---
#[test]
fn terminating_can_only_transition_to_terminated() {
    assert!(State::Terminating.can_transition_to(State::Terminated));
    assert!(!State::Terminating.can_transition_to(State::Idle));
    assert!(!State::Terminating.can_transition_to(State::Running));
    assert!(!State::Terminating.can_transition_to(State::Terminating));
}

// --- Claim: Terminated cannot transition to anything ---
#[test]
fn terminated_cannot_transition() {
    assert!(!State::Terminated.can_transition_to(State::Idle));
    assert!(!State::Terminated.can_transition_to(State::Running));
    assert!(!State::Terminated.can_transition_to(State::Terminating));
    assert!(!State::Terminated.can_transition_to(State::Terminated));
}

// --- Claim: Full lifecycle Idle -> Running -> Terminating -> Terminated ---
#[tokio::test]
async fn full_state_lifecycle() {
    let mut engine = engine_with_mode(Mode::Standalone);
    assert_eq!(engine.state(), State::Idle);

    engine.start().await.unwrap();
    assert_eq!(engine.state(), State::Running);

    engine.terminate().await.unwrap();
    assert_eq!(engine.state(), State::Terminated);
    // Verify terminal
    assert!(engine.state().is_terminal());
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 2: ENGINE CONSTRUCTION CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: Engine::new preserves config mode and starts Idle ---
#[test]
fn engine_new_preserves_config_mode_and_starts_idle() {
    let engine = engine_with_mode(Mode::Coordinator);
    assert_eq!(engine.state(), State::Idle);
    assert_eq!(engine.mode(), Mode::Coordinator);
}

// --- Claim: Engine::default creates Standalone Idle engine ---
#[test]
fn engine_default_creates_standalone_idle() {
    let engine = Engine::default();
    assert_eq!(engine.state(), State::Idle);
    assert_eq!(engine.mode(), Mode::Standalone);
}

// --- Claim: Engine engine_id can be set via config ---
#[test]
fn engine_id_from_config() {
    let engine = Engine::new(Config {
        engine_id: Some("test-engine-42".into()),
        ..Default::default()
    });
    assert_eq!(engine.engine_id(), Some("test-engine-42"));
}

// --- Claim: Engine engine_id defaults to None ---
#[test]
fn engine_id_defaults_to_none() {
    let engine = Engine::default();
    assert!(engine.engine_id().is_none());
}

// --- Claim: set_mode works only when Idle ---
#[test]
fn set_mode_works_when_idle() {
    let mut engine = Engine::default();
    engine.set_mode(Mode::Coordinator);
    assert_eq!(engine.mode(), Mode::Coordinator);
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 3: LIFECYCLE GUARD CONTRACTS (LIAR CHECK)
// ═══════════════════════════════════════════════════════════════════

// --- Claim: start() fails when not Idle ---
#[tokio::test]
async fn start_fails_when_not_idle() {
    let mut engine = engine_with_mode(Mode::Standalone);
    engine.start().await.unwrap();

    let err = engine.start().await.unwrap_err();
    assert!(err.to_string().contains("not idle"));

    engine.terminate().await.unwrap();
}

// --- Claim: terminate() fails when not Running ---
#[tokio::test]
async fn terminate_fails_when_not_running() {
    let mut engine = engine_with_mode(Mode::Standalone);
    let err = engine.terminate().await.unwrap_err();
    assert!(err.to_string().contains("not running"));
}

// --- Claim: submit_job() fails when not Running ---
#[tokio::test]
async fn submit_job_fails_when_not_running() {
    let engine = engine_with_mode(Mode::Standalone);
    let err = engine
        .submit_job(make_job("550e8400-e29b-41d4-a716-446655440501"), vec![])
        .await
        .unwrap_err();
    assert!(err.to_string().contains("not running"));
}

// --- Claim: submit_job() fails in Worker mode ---
#[tokio::test]
async fn submit_job_fails_in_worker_mode() {
    std::env::set_var("TWERK_BROKER_TYPE", "inmemory");
    let mut engine = engine_with_mode(Mode::Worker);
    engine.start().await.unwrap();

    let err = engine
        .submit_job(make_job("550e8400-e29b-41d4-a716-446655440502"), vec![])
        .await
        .unwrap_err();
    assert!(err
        .to_string()
        .contains("not in coordinator/standalone mode"));

    engine.terminate().await.unwrap();
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 4: REGISTRATION GUARD CONTRACTS (BREAKAGE CHECK)
// ═══════════════════════════════════════════════════════════════════

// --- Claim: All registrations silently ignored when not Idle ---
#[tokio::test]
async fn registrations_ignored_when_running() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    std::env::set_var("TWERK_BROKER_TYPE", "inmemory");

    let mut engine = engine_with_mode(Mode::Standalone);
    engine.start().await.unwrap();

    // All of these should be silent no-ops
    engine.register_web_middleware(Arc::new(|_req, _next| {
        Box::pin(async { axum::response::Response::new(axum::body::Body::empty()) })
    }));
    engine.register_task_middleware(Arc::new(|h| h));
    engine.register_job_middleware(Arc::new(|h| h));
    engine.register_node_middleware(Arc::new(|h| h));
    engine.register_log_middleware(Arc::new(|h| h));
    engine.register_endpoint(
        "GET",
        "/noop",
        Arc::new(|_p, _b| {
            Box::pin(async { axum::response::Response::new(axum::body::Body::empty()) })
        }),
    );
    engine.register_runtime(Box::new(twerk_app::engine::MockRuntime));
    engine.register_datastore_provider("noop", Box::new(InMemoryDatastore::new()));
    engine.register_broker_provider("noop", Box::new(InMemoryBroker::new()));

    engine.terminate().await.unwrap();
}

// --- Claim: Runtime registration is first-wins ---
#[test]
fn runtime_registration_is_first_wins() {
    let mut engine = Engine::default();
    engine.register_runtime(Box::new(twerk_app::engine::MockRuntime));
    // Second registration silently ignored
    engine.register_runtime(Box::new(twerk_app::engine::MockRuntime));
}

// --- Claim: Datastore provider registration is first-wins ---
#[test]
fn datastore_provider_first_wins() {
    let mut engine = Engine::default();
    engine.register_datastore_provider("ds1", Box::new(InMemoryDatastore::new()));
    engine.register_datastore_provider("ds1", Box::new(InMemoryDatastore::new()));
}

// --- Claim: Broker provider registration is first-wins ---
#[test]
fn broker_provider_first_wins() {
    let mut engine = Engine::default();
    engine.register_broker_provider("br1", Box::new(InMemoryBroker::new()));
    engine.register_broker_provider("br1", Box::new(InMemoryBroker::new()));
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 5: BROKER PROXY CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: BrokerProxy check_init fails before initialization ---
#[tokio::test]
async fn broker_proxy_check_init_fails_uninitialized() {
    let proxy = BrokerProxy::new();
    let err = proxy.check_init().await.unwrap_err();
    assert!(err.to_string().contains("not initialized"));
}

// --- Claim: BrokerProxy delegates after init ---
#[tokio::test]
async fn broker_proxy_delegates_after_init() {
    let proxy = BrokerProxy::new();
    proxy.init("inmemory", Some("bdd")).await.unwrap();
    proxy.check_init().await.unwrap();
}

// --- Claim: BrokerProxy set_broker enables check_init ---
#[tokio::test]
async fn broker_proxy_set_broker_enables_use() {
    let proxy = BrokerProxy::new();
    proxy.set_broker(Box::new(InMemoryBroker::new())).await;
    proxy.check_init().await.unwrap();
}

// --- Claim: BrokerProxy clone_inner shares state ---
#[tokio::test]
async fn broker_proxy_clone_inner_shares_state() {
    let original = BrokerProxy::new();
    original.init("inmemory", Some("bdd")).await.unwrap();

    let cloned = original.clone_inner();
    cloned.check_init().await.unwrap();
}

// --- Claim: BrokerType::parse maps strings correctly ---
#[test]
fn broker_type_parse_mapping() {
    assert_eq!(BrokerType::parse("inmemory"), BrokerType::InMemory);
    assert_eq!(BrokerType::parse("INMEMORY"), BrokerType::InMemory);
    assert_eq!(BrokerType::parse("InMemory"), BrokerType::InMemory);
    assert_eq!(BrokerType::parse("rabbitmq"), BrokerType::RabbitMQ);
    assert_eq!(BrokerType::parse("RabbitMQ"), BrokerType::RabbitMQ);
    assert_eq!(BrokerType::parse("unknown"), BrokerType::InMemory);
}

// --- Claim: Uninitialized broker proxy returns errors on operations ---
#[tokio::test]
async fn broker_proxy_returns_error_on_operations_when_uninit() {
    let proxy = BrokerProxy::new();
    let result = proxy.health_check().await;
    assert_eq!(
        result.unwrap_err().to_string(),
        "Broker not initialized. You must call engine.Start() first"
    );
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 6: DATASTORE PROXY CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: DatastoreProxy returns errors before initialization ---
#[tokio::test]
async fn datastore_proxy_errors_before_init() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    let proxy = DatastoreProxy::new();
    let result = proxy.health_check().await;
    assert_eq!(
        result,
        Err(twerk_infrastructure::datastore::Error::Database(
            "Datastore not initialized".to_string(),
        ))
    );
}

// --- Claim: DatastoreProxy works after init ---
#[tokio::test]
async fn datastore_proxy_works_after_init() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    let proxy = DatastoreProxy::new();
    proxy.init().await.unwrap();
    proxy.health_check().await.unwrap();
}

// --- Claim: DatastoreProxy works after set_datastore ---
#[tokio::test]
async fn datastore_proxy_works_after_set() {
    let proxy = DatastoreProxy::new();
    proxy
        .set_datastore(Box::new(InMemoryDatastore::new()))
        .await;
    proxy.health_check().await.unwrap();
}

// --- Claim: DatastoreProxy clone_inner shares state ---
#[tokio::test]
async fn datastore_proxy_clone_inner_shares() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    let original = DatastoreProxy::new();
    original.init().await.unwrap();

    let cloned = original.clone_inner();
    cloned.health_check().await.unwrap();
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 7: MIDDLEWARE COMPOSER CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: MiddlewareComposer applies task middleware in LIFO order ---
#[tokio::test]
async fn middleware_composer_applies_task_middleware_lifo() {
    let call_order: Arc<std::sync::Mutex<Vec<usize>>> = Arc::new(std::sync::Mutex::new(Vec::new()));

    let mw1: twerk_app::engine::TaskMiddlewareFunc = {
        let order = call_order.clone();
        Arc::new(move |handler: twerk_app::engine::TaskHandlerFunc| {
            let order = order.clone();
            let composed: twerk_app::engine::TaskHandlerFunc = Arc::new(move |ctx, et, task| {
                order.lock().unwrap().push(1);
                handler(ctx, et, task)
            });
            composed
        })
    };

    let mw2: twerk_app::engine::TaskMiddlewareFunc = {
        let order = call_order.clone();
        Arc::new(move |handler: twerk_app::engine::TaskHandlerFunc| {
            let order = order.clone();
            let composed: twerk_app::engine::TaskHandlerFunc = Arc::new(move |ctx, et, task| {
                order.lock().unwrap().push(2);
                handler(ctx, et, task)
            });
            composed
        })
    };

    let base_handler: twerk_app::engine::TaskHandlerFunc = Arc::new(|_ctx, _et, _task| Ok(()));

    let composer = MiddlewareComposer::new().with_task(mw1).with_task(mw2);

    let composed = composer.compose_task_handler(base_handler);
    let mut task = Task::default();
    composed(Arc::new(()), TaskEventType::Started, &mut task).unwrap();

    let order = call_order.lock().unwrap();
    // rev().fold means mw2 applied first (wrapping base), then mw1 (wrapping mw2+base)
    // So execution: mw1 → mw2 → base
    assert_eq!(order[0], 1);
    assert_eq!(order[1], 2);
}

// --- Claim: MiddlewareComposer with no middleware returns handler unchanged ---
#[tokio::test]
async fn middleware_composer_identity() {
    let call_count = Arc::new(AtomicUsize::new(0));
    let handler: twerk_app::engine::TaskHandlerFunc = {
        let count = call_count.clone();
        Arc::new(move |_ctx, _et, _task| {
            count.fetch_add(1, Ordering::SeqCst);
            Ok(())
        })
    };

    let composer = MiddlewareComposer::new();
    let composed = composer.compose_task_handler(handler);
    let mut task = Task::default();
    composed(Arc::new(()), TaskEventType::Started, &mut task).unwrap();

    assert_eq!(call_count.load(Ordering::SeqCst), 1);
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 8: ENDPOINT REGISTRY CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: EndpointRegistry stores and retrieves endpoints ---
#[test]
fn endpoint_registry_stores_and_retrieves() {
    let handler: EndpointHandler = Arc::new(|_p, _b| {
        Box::pin(async { axum::response::Response::new(axum::body::Body::empty()) })
    });
    let mut reg = EndpointRegistry::new();
    reg.register("GET", "/api/test", handler);

    assert!(reg.contains("GET", "/api/test"));
    assert!(!reg.contains("POST", "/api/test"));
    assert!(!reg.contains("GET", "/api/other"));
    assert!(reg.get("GET", "/api/test").is_some());
}

// --- Claim: EndpointRegistry overwrites on duplicate key ---
#[test]
fn endpoint_registry_overwrites_duplicate() {
    let h1: EndpointHandler = Arc::new(|_p, _b| {
        Box::pin(async { axum::response::Response::new(axum::body::Body::empty()) })
    });
    let h2: EndpointHandler = Arc::new(|_p, _b| {
        Box::pin(async { axum::response::Response::new(axum::body::Body::empty()) })
    });
    let mut reg = EndpointRegistry::new();
    reg.register("GET", "/dup", h1);
    reg.register("GET", "/dup", h2);
    assert_eq!(reg.iter().count(), 1);
}

// --- Claim: EndpointRegistry iter returns all endpoints ---
#[test]
fn endpoint_registry_iter() {
    let h: EndpointHandler = Arc::new(|_p, _b| {
        Box::pin(async { axum::response::Response::new(axum::body::Body::empty()) })
    });
    let mut reg = EndpointRegistry::new();
    reg.register("GET", "/a", h.clone());
    reg.register("POST", "/b", h);
    assert_eq!(reg.iter().count(), 2);
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 9: PROVIDER REGISTRY CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: ProviderRegistry registers and retrieves ---
#[test]
fn provider_registry_registers_and_retrieves() {
    let mut reg = ProviderRegistry::new();
    assert!(!reg.has_datastore("ds1"));

    reg.register_datastore("ds1", Box::new(InMemoryDatastore::new()));
    assert!(reg.has_datastore("ds1"));
    assert!(reg.get_datastore("ds1").is_some());

    reg.register_broker("br1", Box::new(InMemoryBroker::new()));
    assert!(reg.has_broker("br1"));
    assert!(reg.get_broker("br1").is_some());
}

// --- Claim: ProviderRegistry first-wins on duplicate ---
#[test]
fn provider_registry_first_wins() {
    let mut reg = ProviderRegistry::new();
    reg.register_datastore("ds1", Box::new(InMemoryDatastore::new()));
    reg.register_datastore("ds1", Box::new(InMemoryDatastore::new()));
    // Should not panic, and entry exists
    assert!(reg.has_datastore("ds1"));
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 10: MOUNT REGISTRY CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: MountRegistry registers and retrieves per-runtime ---
#[test]
fn mount_registry_registers_per_runtime() {
    let mut reg = MountRegistry::new();
    reg.register_mounter(
        "docker",
        "bind",
        Box::new(BindMounter::new(BindConfig::default())),
    )
    .unwrap();

    assert!(reg.get_mounter("docker").is_some());
    assert!(reg.get_mounter("podman").is_none());

    let runtimes: Vec<_> = reg.runtimes().collect();
    assert!(runtimes.contains(&&"docker".to_string()));
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 11: MOUNTER BEHAVIORAL CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: BindMounter rejects when policy is Denied ---
#[tokio::test]
async fn bind_mounter_rejects_denied_policy() {
    let mounter = BindMounter::new(BindConfig::default());
    let mnt = Mount {
        id: Some("bdd".into()),
        mount_type: Some("bind".into()),
        source: Some("/tmp/bdd".into()),
        target: Some("/mnt/bdd".into()),
        opts: None,
    };
    let err = mounter.mount(&mnt).await.unwrap_err();
    assert!(err.to_string().contains("not allowed"));
}

// --- Claim: BindMounter allows when policy is Allowed with empty list ---
#[tokio::test]
async fn bind_mounter_allows_empty_allowed_list() {
    let mounter = BindMounter::new(BindConfig {
        policy: MountPolicy::Allowed(vec![]),
    });
    let mnt = Mount {
        id: Some("bdd".into()),
        mount_type: Some("bind".into()),
        source: Some("/tmp/bdd-allowed".into()),
        target: Some("/mnt/bdd".into()),
        opts: None,
    };
    mounter.mount(&mnt).await.unwrap();
}

// --- Claim: VolumeMounter requires non-empty id ---
#[tokio::test]
async fn volume_mounter_requires_id() {
    let mounter = VolumeMounter::new();
    let mnt = Mount {
        id: None,
        mount_type: Some("volume".into()),
        source: None,
        target: Some("/data".into()),
        opts: None,
    };
    let err = mounter.mount(&mnt).await.unwrap_err();
    assert!(err.to_string().contains("missing mount id"));
}

// --- Claim: VolumeMounter succeeds with valid mount ---
#[tokio::test]
async fn volume_mounter_succeeds_with_id() {
    let mounter = VolumeMounter::new();
    let mnt = Mount {
        id: Some("vol-1".into()),
        mount_type: Some("volume".into()),
        source: None,
        target: Some("/data".into()),
        opts: None,
    };
    mounter.mount(&mnt).await.unwrap();
}

// --- Claim: TmpfsMounter requires target ---
#[tokio::test]
async fn tmpfs_mounter_requires_target() {
    let mounter = TmpfsMounter::new();
    let mnt = Mount {
        id: Some("t1".into()),
        mount_type: Some("tmpfs".into()),
        source: None,
        target: None,
        opts: None,
    };
    let err = mounter.mount(&mnt).await.unwrap_err();
    assert!(err.to_string().contains("target is required"));
}

// --- Claim: TmpfsMounter rejects non-empty source ---
#[tokio::test]
async fn tmpfs_mounter_rejects_nonempty_source() {
    let mounter = TmpfsMounter::new();
    let mnt = Mount {
        id: Some("t2".into()),
        mount_type: Some("tmpfs".into()),
        source: Some("/bad".into()),
        target: Some("/dev/shm".into()),
        opts: None,
    };
    let err = mounter.mount(&mnt).await.unwrap_err();
    assert!(err.to_string().contains("source should be empty"));
}

// --- Claim: All mounters unmount is a no-op ---
#[tokio::test]
async fn all_mounters_unmount_noop() {
    let mnt = Mount {
        id: Some("u1".into()),
        mount_type: Some("bind".into()),
        source: Some("/tmp".into()),
        target: Some("/mnt".into()),
        opts: None,
    };
    let bind_mounter = BindMounter::new(BindConfig::default());
    Mounter::unmount(&bind_mounter, &mnt).await.unwrap();

    let vol_mounter = VolumeMounter::new();
    Mounter::unmount(&vol_mounter, &mnt).await.unwrap();

    let tmpfs_mounter = TmpfsMounter::new();
    Mounter::unmount(&tmpfs_mounter, &mnt).await.unwrap();
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 12: HOSTENV MIDDLEWARE CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: HostEnv::new rejects invalid specs ---
#[test]
fn hostenv_rejects_invalid_spec() {
    let result = HostEnv::new(&["a:b:c".to_string()]);
    assert_eq!(
        result.map(|_| ()),
        Err("invalid env var spec: a:b:c".to_string())
    );
}

// --- Claim: HostEnv::new accepts single var specs ---
#[test]
fn hostenv_accepts_single_var() {
    let result = HostEnv::new(&["HOME".to_string()]);
    assert_eq!(result.map(|_| ()), Ok(()));
}

// --- Claim: HostEnv::new accepts mapping specs ---
#[test]
fn hostenv_accepts_mapping_spec() {
    let result = HostEnv::new(&["HOST_VAR:TASK_VAR".to_string()]);
    assert_eq!(result.map(|_| ()), Ok(()));
}

// --- Claim: HostEnv middleware injects on StateChange->Running ---
#[tokio::test]
async fn hostenv_middleware_injects_on_statechange_running() {
    std::env::set_var("TWERK_BDD_TEST_VAR", "test-value");
    let hostenv = HostEnv::new(&["TWERK_BDD_TEST_VAR".to_string()]).unwrap();
    let mw = hostenv.middleware();

    let base: twerk_app::engine::TaskHandlerFunc = Arc::new(|_ctx, _et, _task| Ok(()));
    let composed = mw(base);

    let mut task = Task {
        state: TaskState::Running,
        ..Default::default()
    };
    composed(Arc::new(()), TaskEventType::StateChange, &mut task).unwrap();

    let env = task.env.as_ref().unwrap();
    assert_eq!(
        env.get("TWERK_BDD_TEST_VAR"),
        Some(&"test-value".to_string())
    );

    std::env::remove_var("TWERK_BDD_TEST_VAR");
}

// --- Claim: HostEnv middleware does NOT inject on non-Running state ---
#[tokio::test]
async fn hostenv_middleware_skips_non_running_state() {
    std::env::set_var("TWERK_BDD_SKIP_VAR", "should-not-appear");
    let hostenv = HostEnv::new(&["TWERK_BDD_SKIP_VAR".to_string()]).unwrap();
    let mw = hostenv.middleware();

    let base: twerk_app::engine::TaskHandlerFunc = Arc::new(|_ctx, _et, _task| Ok(()));
    let composed = mw(base);

    let mut task = Task {
        state: TaskState::Pending,
        ..Default::default()
    };
    composed(Arc::new(()), TaskEventType::StateChange, &mut task).unwrap();

    assert!(task.env.is_none());
    std::env::remove_var("TWERK_BDD_SKIP_VAR");
}

// --- Claim: HostEnv middleware does NOT inject on non-StateChange event ---
#[tokio::test]
async fn hostenv_middleware_skips_non_statechange_event() {
    std::env::set_var("TWERK_BDD_EVT_VAR", "should-not-appear");
    let hostenv = HostEnv::new(&["TWERK_BDD_EVT_VAR".to_string()]).unwrap();
    let mw = hostenv.middleware();

    let base: twerk_app::engine::TaskHandlerFunc = Arc::new(|_ctx, _et, _task| Ok(()));
    let composed = mw(base);

    let mut task = Task {
        state: TaskState::Running,
        ..Default::default()
    };
    composed(Arc::new(()), TaskEventType::Progress, &mut task).unwrap();

    assert!(task.env.is_none());
    std::env::remove_var("TWERK_BDD_EVT_VAR");
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 13: ERROR TYPE CONTRACTS (COMPLETENESS CHECK)
// ═══════════════════════════════════════════════════════════════════

// --- Claim: TaskHandlerError has Handler and Datastore variants ---
#[test]
fn task_handler_error_variants() {
    let e1 = TaskHandlerError::Handler("msg".into());
    let e2 = TaskHandlerError::Datastore("msg".into());
    assert!(e1.to_string().contains("task handler error"));
    assert!(e2.to_string().contains("task datastore error"));
}

// --- Claim: JobHandlerError has Handler and Datastore variants ---
#[test]
fn job_handler_error_variants() {
    let e1 = JobHandlerError::Handler("msg".into());
    let e2 = JobHandlerError::Datastore("msg".into());
    assert!(e1.to_string().contains("job handler error"));
    assert!(e2.to_string().contains("job datastore error"));
}

// --- Claim: LogHandlerError has Handler and Middleware variants ---
#[test]
fn log_handler_error_variants() {
    let e1 = LogHandlerError::Handler("msg".into());
    let e2 = LogHandlerError::Middleware("msg".into());
    assert!(e1.to_string().contains("log handler error"));
    assert!(e2.to_string().contains("log middleware error"));
}

// --- Claim: NodeHandlerError has Handler and Datastore variants ---
#[test]
fn node_handler_error_variants() {
    let e1 = NodeHandlerError::Handler("msg".into());
    let e2 = NodeHandlerError::Datastore("msg".into());
    assert!(e1.to_string().contains("node handler error"));
    assert!(e2.to_string().contains("node datastore error"));
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 14: EVENT TYPE CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: TaskEventType variants are correct ---
#[test]
fn task_event_type_variants() {
    assert_eq!(TaskEventType::Started, TaskEventType::Started);
    assert_ne!(TaskEventType::Started, TaskEventType::StateChange);
    assert_ne!(TaskEventType::StateChange, TaskEventType::Redelivered);
    assert_ne!(TaskEventType::Redelivered, TaskEventType::Progress);
}

// --- Claim: JobEventType variants are correct ---
#[test]
fn job_event_type_variants() {
    assert_eq!(JobEventType::StateChange, JobEventType::StateChange);
    assert_ne!(JobEventType::StateChange, JobEventType::Progress);
    assert_ne!(JobEventType::Progress, JobEventType::Read);
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 15: TOPIC CONSTANTS CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: Topic constants have expected values ---
#[test]
fn topic_constants() {
    assert_eq!(twerk_app::engine::TOPIC_JOB, "job.*");
    assert_eq!(twerk_app::engine::TOPIC_JOB_COMPLETED, "job.completed");
    assert_eq!(twerk_app::engine::TOPIC_JOB_FAILED, "job.failed");
    assert_eq!(twerk_app::engine::TOPIC_JOB_PROGRESS, "job.progress");
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 16: CONFIG & MIDDLEWARE DEFAULTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: Config::default creates Standalone with no engine_id ---
#[test]
fn config_defaults() {
    let cfg = Config::default();
    assert_eq!(cfg.mode, Mode::Standalone);
    assert!(cfg.engine_id.is_none());
    assert!(cfg.hostname.is_none());
    assert!(cfg.middleware.web.is_empty());
    assert!(cfg.middleware.task.is_empty());
    assert!(cfg.middleware.job.is_empty());
    assert!(cfg.middleware.node.is_empty());
    assert!(cfg.middleware.log.is_empty());
    assert!(cfg.endpoints.is_empty());
}

// --- Claim: Middleware::default has empty vecs ---
#[test]
fn middleware_defaults() {
    let mw = Middleware::default();
    assert!(mw.web.is_empty());
    assert!(mw.task.is_empty());
    assert!(mw.job.is_empty());
    assert!(mw.node.is_empty());
    assert!(mw.log.is_empty());
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 17: WORKER LIMITS CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: Limits defaults match constants ---
#[test]
fn limits_defaults() {
    let limits = Limits::default();
    assert_eq!(limits.cpus, "");
    assert_eq!(limits.memory, "");
    assert_eq!(limits.timeout, "");
}

// --- Claim: Worker default constants have expected values ---
#[test]
fn worker_default_constants() {
    assert_eq!(twerk_app::engine::worker::DEFAULT_CPUS_LIMIT, "1");
    assert_eq!(twerk_app::engine::worker::DEFAULT_MEMORY_LIMIT, "512m");
    assert_eq!(twerk_app::engine::worker::DEFAULT_TIMEOUT, "5m");
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 18: COORDINATOR INTEGRATION CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: Coordinator submit_job creates job in datastore ---
#[tokio::test]
async fn coordinator_submit_job_persists() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    let broker = BrokerProxy::new();
    let ds = DatastoreProxy::new();
    broker.init("inmemory", Some("bdd")).await.unwrap();
    ds.init().await.unwrap();

    let coord = twerk_app::engine::coordinator::create_coordinator(broker.clone(), ds.clone())
        .await
        .unwrap();
    coord.start().await.unwrap();

    let job = make_job("550e8400-e29b-41d4-a716-446655440503");
    coord.submit_job(job.clone()).await.unwrap();

    let persisted = ds.get_job_by_id(job.id.as_deref().unwrap()).await.unwrap();
    assert_eq!(persisted.id, job.id);

    coord.stop().await.unwrap();
}

// --- Claim: Coordinator generates ID when missing ---
#[tokio::test]
async fn coordinator_generates_id_when_missing() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    let broker = BrokerProxy::new();
    let ds = DatastoreProxy::new();
    broker.init("inmemory", Some("bdd")).await.unwrap();
    ds.init().await.unwrap();

    let coord = twerk_app::engine::coordinator::create_coordinator(broker, ds)
        .await
        .unwrap();
    coord.start().await.unwrap();

    let job = Job {
        id: None,
        state: JobState::Pending,
        ..Default::default()
    };
    let result = coord.submit_job(job).await.unwrap();
    assert!(result.id.is_some());

    coord.stop().await.unwrap();
}

// --- Claim: Coordinator sets created_at on submission ---
#[tokio::test]
async fn coordinator_sets_created_at() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    let broker = BrokerProxy::new();
    let ds = DatastoreProxy::new();
    broker.init("inmemory", Some("bdd")).await.unwrap();
    ds.init().await.unwrap();

    let coord = twerk_app::engine::coordinator::create_coordinator(broker, ds)
        .await
        .unwrap();
    coord.start().await.unwrap();

    let job = Job {
        id: Some(to_job_id("550e8400-e29b-41d4-a716-446655440504")),
        state: JobState::Pending,
        created_at: None,
        ..Default::default()
    };
    let result = coord.submit_job(job).await.unwrap();
    assert!(result.created_at.is_some());

    coord.stop().await.unwrap();
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 19: JOB LISTENER CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: Job listeners can be added to engine ---
// NOTE: add_job_listener uses blocking_write(), so cannot be called from
// within a tokio runtime. This is a BREAKAGE CHECK finding: the public API
// is incompatible with async contexts.
#[test]
fn job_listeners_can_be_added_outside_runtime() {
    let counter = Arc::new(AtomicUsize::new(0));
    let listener: JobListener = {
        let c = counter.clone();
        Arc::new(move |_job| {
            c.fetch_add(1, Ordering::SeqCst);
        })
    };

    let engine = Engine::default();
    engine.add_job_listener(listener);
    // Listener registered without panic
    assert_eq!(counter.load(Ordering::SeqCst), 0); // not invoked yet
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 20: DEBUG IMPLEMENTATION CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: Engine Debug shows state and mode ---
#[test]
fn engine_debug_shows_state_mode() {
    let engine = Engine::default();
    let dbg = format!("{engine:?}");
    assert!(dbg.contains("Idle"));
    assert!(dbg.contains("Standalone"));
}

// --- Claim: BrokerProxy Debug doesn't panic ---
#[test]
fn broker_proxy_debug() {
    let proxy = BrokerProxy::new();
    let _dbg = format!("{proxy:?}");
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 21: AWAIT SHUTDOWN CONTRACTS (BREAKAGE CHECK)
// ═══════════════════════════════════════════════════════════════════

// --- Claim: run() starts and terminates engine correctly ---
#[tokio::test]
async fn run_completes_full_lifecycle() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    std::env::set_var("TWERK_BROKER_TYPE", "inmemory");

    let mut engine = engine_with_mode(Mode::Standalone);
    engine.start().await.unwrap();
    engine.terminate().await.unwrap();
    // Engine reached terminal state
    assert_eq!(engine.state(), State::Terminated);
    assert!(engine.state().is_terminal());
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 22: MULTI-MODE START CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: Standalone mode starts both worker and coordinator ---
#[tokio::test]
async fn standalone_starts_worker_and_coordinator() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    std::env::set_var("TWERK_BROKER_TYPE", "inmemory");

    let mut engine = engine_with_mode(Mode::Standalone);
    engine.start().await.unwrap();
    assert_eq!(engine.state(), State::Running);

    engine.terminate().await.unwrap();
    assert_eq!(engine.state(), State::Terminated);
}

// --- Claim: Coordinator mode starts coordinator only ---
#[tokio::test]
async fn coordinator_mode_starts_coordinator() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    std::env::set_var("TWERK_BROKER_TYPE", "inmemory");

    let mut engine = engine_with_mode(Mode::Coordinator);
    engine.start().await.unwrap();
    assert_eq!(engine.state(), State::Running);

    engine.terminate().await.unwrap();
}

// --- Claim: Worker mode starts worker only ---
#[tokio::test]
async fn worker_mode_starts_worker() {
    std::env::set_var("TWERK_BROKER_TYPE", "inmemory");
    std::env::set_var("TWERK_RUNTIME_TYPE", "shell");
    std::env::set_var("TWERK_RUNTIME_SHELL_CMD", "bash");

    let mut engine = engine_with_mode(Mode::Worker);
    engine.start().await.unwrap();
    assert_eq!(engine.state(), State::Running);

    engine.terminate().await.unwrap();

    std::env::remove_var("TWERK_RUNTIME_TYPE");
    std::env::remove_var("TWERK_RUNTIME_SHELL_CMD");
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 23: ENDPOINT REGISTRATION VIA ENGINE
// ═══════════════════════════════════════════════════════════════════

// --- Claim: Engine endpoint registration uses "METHOD path" key format ---
#[test]
fn engine_endpoint_key_format() {
    let handler: EndpointHandler = Arc::new(|_p, _b| {
        Box::pin(async { axum::response::Response::new(axum::body::Body::empty()) })
    });
    let mut reg = EndpointRegistry::new();
    reg.register("POST", "/api/jobs", handler);
    assert!(reg.contains("POST", "/api/jobs"));
    assert!(!reg.contains("GET", "/api/jobs"));
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 24: MOCK RUNTIME CONTRACT (COMPLETENESS CHECK)
// ═══════════════════════════════════════════════════════════════════

// --- Claim: MockRuntime can be constructed and used ---
#[tokio::test]
async fn mock_runtime_is_usable() {
    let rt = twerk_app::engine::MockRuntime;
    let task = Task::default();
    Runtime::run(&rt, &task).await.unwrap();
    let _ = Runtime::stop(&rt, &task).await;
    Runtime::health_check(&rt).await.unwrap();
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 25: FACTORY FUNCTION CONTRACTS
// ═══════════════════════════════════════════════════════════════════

// --- Claim: create_broker("inmemory") produces healthy broker ---
#[tokio::test]
async fn create_broker_inmemory() {
    use twerk_app::engine::broker::create_broker;
    let broker = create_broker("inmemory", Some("bdd")).await.unwrap();
    broker.health_check().await.unwrap();
}

// --- Claim: create_datastore with inmemory produces healthy datastore ---
#[tokio::test]
async fn create_datastore_inmemory() {
    use twerk_app::engine::datastore::create_datastore;
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    let ds = create_datastore().await.unwrap();
    ds.health_check().await.unwrap();
}

// --- Claim: new_inmemory_datastore produces healthy datastore ---
#[tokio::test]
async fn new_inmemory_datastore_works() {
    use twerk_app::engine::datastore::new_inmemory_datastore;
    let ds = new_inmemory_datastore();
    ds.health_check().await.unwrap();
}

// ═══════════════════════════════════════════════════════════════════
// SECTION 26: SUBMIT_JOB END-TO-END IN STANDALONE
// ═══════════════════════════════════════════════════════════════════

// --- Claim: submit_job works in Standalone mode with coordinator available ---
#[tokio::test]
async fn submit_job_standalone_e2e() {
    std::env::set_var("TWERK_DATASTORE_TYPE", "inmemory");
    std::env::set_var("TWERK_BROKER_TYPE", "inmemory");

    let mut engine = engine_with_mode(Mode::Standalone);
    engine.start().await.unwrap();

    let job = make_job("550e8400-e29b-41d4-a716-446655440505");
    let result = engine.submit_job(job.clone(), vec![]).await.unwrap();
    assert_eq!(result.id, job.id);

    engine.terminate().await.unwrap();
}
